#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-javax.servlet-api
Version  : 3.1.0
Release  : 3
URL      : https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar
Source0  : https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar
Source1  : https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : CDDL-1.0
Requires: mvn-javax.servlet-api-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-javax.servlet-api package.
Group: Data

%description data
data components for the mvn-javax.servlet-api package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/servlet/javax.servlet-api/3.1.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/javax/servlet/javax.servlet-api/3.1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar
/usr/share/java/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom
